# Generated by Django 2.2.17 on 2020-11-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0002_meter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meter',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meter',
            old_name='VerificationDate',
            new_name='verificationDate',
        ),
    ]
