# Generated by Django 2.2.17 on 2020-11-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meters', '0005_auto_20201116_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='value',
            field=models.FloatField(),
        ),
    ]
